[package]
name = "crypto_module"
version = "0.1.0"
authors = ["Drilon Buzuku <drilon.buku@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
serde = "1.0.83"
serde_derive = "1.0.83"
serde_json = "1.0.34"
toml = "0.4.10"
